//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace notedump.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("notedump.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anime
        ///.
        /// </summary>
        internal static string nd_get_anime {
            get {
                return ResourceManager.GetString("nd_get_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to books.
        /// </summary>
        internal static string nd_get_books {
            get {
                return ResourceManager.GetString("nd_get_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games
        ///.
        /// </summary>
        internal static string nd_get_games {
            get {
                return ResourceManager.GetString("nd_get_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all links.
        /// </summary>
        internal static string nd_links_all {
            get {
                return ResourceManager.GetString("nd_links_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to links - articles.
        /// </summary>
        internal static string nd_links_arts {
            get {
                return ResourceManager.GetString("nd_links_arts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to links - youtube
        ///.
        /// </summary>
        internal static string nd_links_yt {
            get {
                return ResourceManager.GetString("nd_links_yt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get - movies.
        /// </summary>
        internal static string nd_movies {
            get {
                return ResourceManager.GetString("nd_movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music - all.
        /// </summary>
        internal static string nd_music_all {
            get {
                return ResourceManager.GetString("nd_music_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music - indie
        ///- band1
        ///- band2.
        /// </summary>
        internal static string nd_music_indie {
            get {
                return ResourceManager.GetString("nd_music_indie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music - metal
        ///- band1
        ///- band2.
        /// </summary>
        internal static string nd_music_metal {
            get {
                return ResourceManager.GetString("nd_music_metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to do: reminders.
        /// </summary>
        internal static string nd_td_remind {
            get {
                return ResourceManager.GetString("nd_td_remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to do: to do.
        /// </summary>
        internal static string nd_td_td {
            get {
                return ResourceManager.GetString("nd_td_td", resourceCulture);
            }
        }
    }
}
